# Generated by Django 2.0.7 on 2018-10-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='code',
            field=models.CharField(help_text='Internal facing reference to product', max_length=30),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='date_end',
            field=models.DateField(blank=True, help_text='Last date card is valid', null=True),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='date_start',
            field=models.DateField(help_text='First date card is valid'),
        ),
    ]
